### ISSUE TITLE
上游代理设置

### ISSUE THREAD

**Issue by Zxis233** [Xerxes-2/MajsoulMax-rs#1]
请问如何设置上游代理呢？想走clash，不然加载太慢

**Comment by Xerxes-2** [comment]
目前不支持上游代理

**Comment by ruanyuanfeng** [comment]
我怎么搞那个[hudsucker] 用cargo编译后不会用

**Comment by Xerxes-2** [comment]
> 我怎么搞那个[hudsucker] 用cargo编译后不会用

不用管这个，这个是上游依赖，和终端用户没关系
